# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.screens_stack = QtWidgets.QStackedWidget(self.centralwidget)
        self.screens_stack.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.screens_stack.sizePolicy().hasHeightForWidth())
        self.screens_stack.setSizePolicy(sizePolicy)
        self.screens_stack.setObjectName("screens_stack")
        self.main_menu = QtWidgets.QWidget()
        self.main_menu.setStyleSheet("QWidget#main_menu {\n"
"border-image: url(:/bg/background.jpg) 0 0 0 0 stretch stretch;\n"
"}")
        self.main_menu.setObjectName("main_menu")
        self.main_menu_buttons = QtWidgets.QFrame(self.main_menu)
        self.main_menu_buttons.setGeometry(QtCore.QRect(720, 480, 500, 500))
        self.main_menu_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_menu_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_menu_buttons.setObjectName("main_menu_buttons")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_menu_buttons)
        self.verticalLayout.setObjectName("verticalLayout")
        self.startExamBtn = QtWidgets.QPushButton(self.main_menu_buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startExamBtn.sizePolicy().hasHeightForWidth())
        self.startExamBtn.setSizePolicy(sizePolicy)
        self.startExamBtn.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: #007C80;\n"
"    font-weight: bold;\n"
"    font-size: 50px;\n"
"    font-family: \"Comic Sans MS\", cursive;\n"
"    padding: 20px;\n"
"    transition: transform 1s ease-in-out, font-size 1s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    transform: rotate(10deg);\n"
"    font-size: 60px;\n"
"}\n"
"")
        self.startExamBtn.setObjectName("startExamBtn")
        self.verticalLayout.addWidget(self.startExamBtn)
        self.setGearBtn = QtWidgets.QPushButton(self.main_menu_buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setGearBtn.sizePolicy().hasHeightForWidth())
        self.setGearBtn.setSizePolicy(sizePolicy)
        self.setGearBtn.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: #FBB117;\n"
"    font-weight: bold;\n"
"    font-size: 50px;\n"
"    font-family: \"Comic Sans MS\", cursive;\n"
"    padding: 20px;\n"
"    transition: transform 0.3s ease-in-out, font-size 0.3s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    transform: rotate(10deg);\n"
"    font-size: 60px;\n"
"}\n"
"")
        self.setGearBtn.setObjectName("setGearBtn")
        self.verticalLayout.addWidget(self.setGearBtn)
        self.msgCenterBtn = QtWidgets.QPushButton(self.main_menu_buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msgCenterBtn.sizePolicy().hasHeightForWidth())
        self.msgCenterBtn.setSizePolicy(sizePolicy)
        self.msgCenterBtn.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: #F62217;\n"
"    font-weight: bold;\n"
"    font-size: 45px;\n"
"    font-family: \"Comic Sans MS\", cursive;\n"
"    padding: 20px;\n"
"    transition: transform 1s ease-in-out, font-size 1s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    transform: rotate(10deg);\n"
"    font-size: 55px;\n"
"}\n"
"")
        self.msgCenterBtn.setObjectName("msgCenterBtn")
        self.verticalLayout.addWidget(self.msgCenterBtn)
        self.exitBtn = QtWidgets.QPushButton(self.main_menu_buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitBtn.sizePolicy().hasHeightForWidth())
        self.exitBtn.setSizePolicy(sizePolicy)
        self.exitBtn.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: #6C2DC7;\n"
"    font-weight: bold;\n"
"    font-size: 50px;\n"
"    font-family: \"Comic Sans MS\", cursive;\n"
"    padding: 20px;\n"
"    transition: transform 0.3s ease-in-out, font-size 0.3s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    transform: rotate(10deg);\n"
"    font-size: 60px;\n"
"}\n"
"")
        self.exitBtn.setObjectName("exitBtn")
        self.verticalLayout.addWidget(self.exitBtn)
        self.eyeAnimation = QtWidgets.QFrame(self.main_menu)
        self.eyeAnimation.setGeometry(QtCore.QRect(830, 160, 291, 141))
        self.eyeAnimation.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.eyeAnimation.setFrameShadow(QtWidgets.QFrame.Raised)
        self.eyeAnimation.setObjectName("eyeAnimation")
        self.left_eye_lens = QtWidgets.QLabel(self.eyeAnimation)
        self.left_eye_lens.setGeometry(QtCore.QRect(190, 48, 60, 60))
        self.left_eye_lens.setText("")
        self.left_eye_lens.setPixmap(QtGui.QPixmap(":/eyeAnimation/eyeLence.png"))
        self.left_eye_lens.setScaledContents(True)
        self.left_eye_lens.setObjectName("left_eye_lens")
        self.right_eye_lens = QtWidgets.QLabel(self.eyeAnimation)
        self.right_eye_lens.setGeometry(QtCore.QRect(40, 50, 60, 60))
        self.right_eye_lens.setText("")
        self.right_eye_lens.setPixmap(QtGui.QPixmap(":/eyeAnimation/eyeLence.png"))
        self.right_eye_lens.setScaledContents(True)
        self.right_eye_lens.setObjectName("right_eye_lens")
        self.eyeballs = QtWidgets.QLabel(self.eyeAnimation)
        self.eyeballs.setGeometry(QtCore.QRect(0, 0, 291, 141))
        self.eyeballs.setText("")
        self.eyeballs.setPixmap(QtGui.QPixmap(":/eyeAnimation/eyeball.png"))
        self.eyeballs.setScaledContents(True)
        self.eyeballs.setObjectName("eyeballs")
        self.eyeballs.raise_()
        self.right_eye_lens.raise_()
        self.left_eye_lens.raise_()
        self.peeking_boy_label = QtWidgets.QLabel(self.main_menu)
        self.peeking_boy_label.setGeometry(QtCore.QRect(714, 110, 511, 291))
        self.peeking_boy_label.setText("")
        self.peeking_boy_label.setPixmap(QtGui.QPixmap(":/eyeAnimation/boy peeks.png"))
        self.peeking_boy_label.setScaledContents(True)
        self.peeking_boy_label.setObjectName("peeking_boy_label")
        self.label = QtWidgets.QLabel(self.main_menu)
        self.label.setGeometry(QtCore.QRect(730, 320, 491, 141))
        self.label.setStyleSheet("border: none;\n"
"background-color: transparent;\n"
"color: #B2A4FF;\n"
"font-weight: bold;\n"
"font-size: 100px;\n"
"font-family: \"Comic Sans MS\", cursive;\n"
"\n"
"transition: transform 1s ease-in-out, font-size 1s ease-in-out;")
        self.label.setObjectName("label")
        self.label.raise_()
        self.peeking_boy_label.raise_()
        self.main_menu_buttons.raise_()
        self.eyeAnimation.raise_()
        self.screens_stack.addWidget(self.main_menu)
        self.start_exam_screen1 = QtWidgets.QWidget()
        self.start_exam_screen1.setStyleSheet("QWidget#start_exam_screen1 {\n"
"border-image: url(:/bg/background.jpg) 0 0 0 0 stretch stretch;\n"
"}")
        self.start_exam_screen1.setObjectName("start_exam_screen1")
        self.info_frame = QtWidgets.QFrame(self.start_exam_screen1)
        self.info_frame.setGeometry(QtCore.QRect(100, 150, 707, 761))
        self.info_frame.setStyleSheet("QFrame#info_frame{\n"
"background-color: rgba(0, 0, 0,180);\n"
"border: 3px solid black;\n"
"border-radius: 25px;\n"
"}")
        self.info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info_frame.setObjectName("info_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.info_frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.headline1_frame = QtWidgets.QFrame(self.info_frame)
        self.headline1_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.headline1_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.headline1_frame.setObjectName("headline1_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.headline1_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.headline1_label = QtWidgets.QLabel(self.headline1_frame)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,cursive")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.headline1_label.setFont(font)
        self.headline1_label.setStyleSheet("QLabel {\n"
"    color: #B2A4FF;\n"
"    font-size: 50px;\n"
"    font-weight: bold;\n"
"    font-family: \"Comic Sans MS\", cursive;\n"
"}")
        self.headline1_label.setObjectName("headline1_label")
        self.verticalLayout_3.addWidget(self.headline1_label)
        self.verticalLayout_6.addWidget(self.headline1_frame)
        self.name_frame = QtWidgets.QFrame(self.info_frame)
        self.name_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.name_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.name_frame.setObjectName("name_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.name_frame)
        self.horizontalLayout.setContentsMargins(40, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name_label = QtWidgets.QLabel(self.name_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label.sizePolicy().hasHeightForWidth())
        self.name_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,cursive")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.name_label.setFont(font)
        self.name_label.setStyleSheet("QLabel {\n"
"    color: #FFB4B4;\n"
"    font-size: 35px;\n"
"    font-weight: bold;\n"
"    font-family: \"Comic Sans MS\", cursive;\n"
"    padding: 10px;\n"
"}")
        self.name_label.setObjectName("name_label")
        self.horizontalLayout.addWidget(self.name_label)
        self.name_lineEdit = QtWidgets.QLineEdit(self.name_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_lineEdit.sizePolicy().hasHeightForWidth())
        self.name_lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,cursive")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.name_lineEdit.setFont(font)
        self.name_lineEdit.setStyleSheet("QLineEdit {\n"
"    font-weight: bold;\n"
"    font-size: 35px;\n"
"    font-family: \"Comic Sans MS\", cursive;\n"
"    padding-left: 10px;\n"
"    border: 2px solid #FFB4B4;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: #B0E0E6; /* Pastel Green color */\n"
"}\n"
"\n"
"    QLineEdit::cursor {\n"
"        width: 4px;\n"
"    }")
        self.name_lineEdit.setText("")
        self.name_lineEdit.setMaxLength(32771)
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.horizontalLayout.addWidget(self.name_lineEdit)
        self.verticalLayout_6.addWidget(self.name_frame)
        self.age_frame = QtWidgets.QFrame(self.info_frame)
        self.age_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.age_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.age_frame.setObjectName("age_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.age_frame)
        self.horizontalLayout_2.setContentsMargins(40, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.age_label = QtWidgets.QLabel(self.age_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.age_label.sizePolicy().hasHeightForWidth())
        self.age_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,cursive")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.age_label.setFont(font)
        self.age_label.setStyleSheet("QLabel {\n"
"    color: #FFDEB4;\n"
"    font-size: 35px;\n"
"    font-weight: bold;\n"
"    font-family: \"Comic Sans MS\", cursive;\n"
"    padding: 10px;\n"
"}")
        self.age_label.setObjectName("age_label")
        self.horizontalLayout_2.addWidget(self.age_label)
        self.age_lineEdit = QtWidgets.QLineEdit(self.age_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.age_lineEdit.sizePolicy().hasHeightForWidth())
        self.age_lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,cursive")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.age_lineEdit.setFont(font)
        self.age_lineEdit.setStyleSheet("QLineEdit {\n"
"    font-weight: bold;\n"
"    font-size: 35px;\n"
"    font-family: \"Comic Sans MS\", cursive;\n"
"    padding-left: 10px;\n"
"    border: 2px solid #FFDEB4;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: #B0E0E6; /* Pastel Green color */\n"
"}\n"
"\n"
"QLineEdit::cursor {\n"
"        width: 4px;\n"
"    }")
        self.age_lineEdit.setObjectName("age_lineEdit")
        self.horizontalLayout_2.addWidget(self.age_lineEdit)
        self.verticalLayout_6.addWidget(self.age_frame)
        self.gender_frame = QtWidgets.QFrame(self.info_frame)
        self.gender_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gender_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gender_frame.setObjectName("gender_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.gender_frame)
        self.horizontalLayout_3.setContentsMargins(40, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gender_label = QtWidgets.QLabel(self.gender_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gender_label.sizePolicy().hasHeightForWidth())
        self.gender_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,cursive")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.gender_label.setFont(font)
        self.gender_label.setStyleSheet("QLabel {\n"
"    color: #6E85B7;\n"
"    font-size: 35px;\n"
"    font-weight: bold;\n"
"    font-family: \"Comic Sans MS\", cursive;\n"
"    padding: 10px;\n"
"}")
        self.gender_label.setObjectName("gender_label")
        self.horizontalLayout_3.addWidget(self.gender_label)
        self.gender_cb = QtWidgets.QComboBox(self.gender_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gender_cb.sizePolicy().hasHeightForWidth())
        self.gender_cb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,cursive")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.gender_cb.setFont(font)
        self.gender_cb.setStyleSheet("QComboBox {\n"
"    font-weight: bold;\n"
"    font-family: \"Comic Sans MS\", cursive;\n"
"    padding: 5px;\n"
"    font-size: 35px;\n"
"    padding-left: 15px;\n"
"    border: 2px solid #6E85B7;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border-color: #B0E0E6; /* Pastel Green color */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: center right;\n"
"    width: 25px;\n"
"    border-left-width: 1px;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    background: transparent;\n"
"}")
        self.gender_cb.setObjectName("gender_cb")
        self.gender_cb.addItem("")
        self.gender_cb.addItem("")
        self.horizontalLayout_3.addWidget(self.gender_cb)
        self.verticalLayout_6.addWidget(self.gender_frame)
        self.contact_frame = QtWidgets.QFrame(self.info_frame)
        self.contact_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contact_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contact_frame.setObjectName("contact_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.contact_frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.contact_label = QtWidgets.QLabel(self.contact_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contact_label.sizePolicy().hasHeightForWidth())
        self.contact_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,cursive")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.contact_label.setFont(font)
        self.contact_label.setStyleSheet("QLabel {\n"
"    color: #007C80;\n"
"    font-size: 40px;\n"
"    font-weight: bold;\n"
"    font-family: \"Comic Sans MS\", cursive;\n"
"}")
        self.contact_label.setObjectName("contact_label")
        self.verticalLayout_4.addWidget(self.contact_label)
        self.verticalLayout_6.addWidget(self.contact_frame)
        self.email_frame = QtWidgets.QFrame(self.info_frame)
        self.email_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.email_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.email_frame.setObjectName("email_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.email_frame)
        self.horizontalLayout_4.setContentsMargins(40, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.email_label = QtWidgets.QLabel(self.email_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.email_label.sizePolicy().hasHeightForWidth())
        self.email_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,cursive")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.email_label.setFont(font)
        self.email_label.setStyleSheet("QLabel {\n"
"    color: #6C2DC7;\n"
"    font-size: 35px;\n"
"    font-weight: bold;\n"
"    font-family: \"Comic Sans MS\", cursive;\n"
"    padding: 10px;\n"
"}")
        self.email_label.setObjectName("email_label")
        self.horizontalLayout_4.addWidget(self.email_label)
        self.email_lineEdit = QtWidgets.QLineEdit(self.email_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.email_lineEdit.sizePolicy().hasHeightForWidth())
        self.email_lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,cursive")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.email_lineEdit.setFont(font)
        self.email_lineEdit.setStyleSheet("QLineEdit {\n"
"    font-weight: bold;\n"
"    font-family: \"Comic Sans MS\", cursive;\n"
"    padding-left: 10px;\n"
"    font-size: 35px;\n"
"    border: 2px solid #6C2DC7;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: #B0E0E6; /* Pastel Green color */\n"
"}\n"
"\n"
"QLineEdit::cursor {\n"
"        width: 4px;\n"
"    }")
        self.email_lineEdit.setText("")
        self.email_lineEdit.setObjectName("email_lineEdit")
        self.horizontalLayout_4.addWidget(self.email_lineEdit)
        self.verticalLayout_6.addWidget(self.email_frame)
        self.frame = QtWidgets.QFrame(self.info_frame)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,cursive")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("QCheckBox {\n"
"    color: #AAC4FF;\n"
"    font-weight: bold;\n"
"    font-size: 23px;\n"
"    font-family: \"Comic Sans MS\", cursive;\n"
"\n"
"    margin-left: 21px\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_6.addWidget(self.checkBox)
        self.terms_condition_btn = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,cursive")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.terms_condition_btn.setFont(font)
        self.terms_condition_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.terms_condition_btn.setStyleSheet("    color: #AAC4FF;\n"
"    font-weight: bold;\n"
"    font-size: 23px;\n"
"    text-decoration: underline;\n"
"    font-family: \"Comic Sans MS\", cursive;\n"
"    margin-right: 26 px;\n"
"    background-color: transparent;")
        self.terms_condition_btn.setObjectName("terms_condition_btn")
        self.horizontalLayout_6.addWidget(self.terms_condition_btn)
        self.verticalLayout_6.addWidget(self.frame)
        self.start_exam_frame = QtWidgets.QFrame(self.start_exam_screen1)
        self.start_exam_frame.setGeometry(QtCore.QRect(1410, 870, 341, 111))
        self.start_exam_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.start_exam_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.start_exam_frame.setObjectName("start_exam_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.start_exam_frame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.start_exam_btn = QtWidgets.QPushButton(self.start_exam_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_exam_btn.sizePolicy().hasHeightForWidth())
        self.start_exam_btn.setSizePolicy(sizePolicy)
        self.start_exam_btn.setStyleSheet("QPushButton#start_exam_btn {\n"
"    background-color: #F3D8FF;\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    padding: 10px;\n"
"    font-size: 40px;\n"
"    font-weight: bold;\n"
"    font-family: \"Comic Sans MS\", cursive;\n"
"}\n"
"\n"
"QPushButton:hover#start_exam_btn {\n"
"    background-color: #F6EEA1;\n"
"    font-size: 50px;\n"
"}\n"
"\n"
"\n"
"QFrame#start_exam_btn {\n"
"    border: 2px dashed #FFA4D1;\n"
"    border-radius: 10px;\n"
"}")
        self.start_exam_btn.setObjectName("start_exam_btn")
        self.verticalLayout_7.addWidget(self.start_exam_btn)
        self.screens_stack.addWidget(self.start_exam_screen1)
        self.start_exam_screen2 = QtWidgets.QWidget()
        self.start_exam_screen2.setStyleSheet("")
        self.start_exam_screen2.setObjectName("start_exam_screen2")
        self.videoWidget = QtWidgets.QWidget(self.start_exam_screen2)
        self.videoWidget.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.videoWidget.setObjectName("videoWidget")
        self.screens_stack.addWidget(self.start_exam_screen2)
        self.exam_results = QtWidgets.QWidget()
        self.exam_results.setStyleSheet("QWidget#exam_results {\n"
"border-image: url(:/bg/background.jpg) 0 0 0 0 stretch stretch;\n"
"}")
        self.exam_results.setObjectName("exam_results")
        self.results_frame = QtWidgets.QFrame(self.exam_results)
        self.results_frame.setGeometry(QtCore.QRect(100, 220, 1031, 551))
        self.results_frame.setStyleSheet("QFrame#results_frame{\n"
"background-color: rgba(0, 0, 0,180);\n"
"border: 3px solid black;\n"
"border-radius: 25px;\n"
"}")
        self.results_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.results_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.results_frame.setObjectName("results_frame")
        self.headline = QtWidgets.QLabel(self.results_frame)
        self.headline.setGeometry(QtCore.QRect(20, 30, 421, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headline.sizePolicy().hasHeightForWidth())
        self.headline.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,cursive")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.headline.setFont(font)
        self.headline.setStyleSheet("QLabel {\n"
"    color: #FFDEB4;\n"
"    font-size: 40px;\n"
"    font-weight: bold;\n"
"    font-family: \"Comic Sans MS\", cursive;\n"
"    padding: 10px;\n"
"}")
        self.headline.setObjectName("headline")
        self.email_sent_label = QtWidgets.QLabel(self.results_frame)
        self.email_sent_label.setGeometry(QtCore.QRect(40, 150, 931, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,cursive")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.email_sent_label.setFont(font)
        self.email_sent_label.setStyleSheet("QLabel {\n"
"    color: #FFDEB4;\n"
"    font-size: 28px;\n"
"    font-weight: bold;\n"
"    font-family: \"Comic Sans MS\", cursive;\n"
"    padding: 10px;\n"
"}")
        self.email_sent_label.setObjectName("email_sent_label")
        self.direct_donwload_frame = QtWidgets.QFrame(self.results_frame)
        self.direct_donwload_frame.setGeometry(QtCore.QRect(30, 250, 931, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.direct_donwload_frame.sizePolicy().hasHeightForWidth())
        self.direct_donwload_frame.setSizePolicy(sizePolicy)
        self.direct_donwload_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.direct_donwload_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.direct_donwload_frame.setObjectName("direct_donwload_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.direct_donwload_frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.directD_label = QtWidgets.QLabel(self.direct_donwload_frame)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS,cursive")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.directD_label.setFont(font)
        self.directD_label.setStyleSheet("QLabel {\n"
"    color: #FFDEB4;\n"
"    font-size: 28px;\n"
"    font-weight: bold;\n"
"    font-family: \"Comic Sans MS\", cursive;\n"
"    padding: 10px;\n"
"}")
        self.directD_label.setObjectName("directD_label")
        self.horizontalLayout_5.addWidget(self.directD_label)
        self.donwloadPDF_button = QtWidgets.QPushButton(self.direct_donwload_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.donwloadPDF_button.sizePolicy().hasHeightForWidth())
        self.donwloadPDF_button.setSizePolicy(sizePolicy)
        self.donwloadPDF_button.setStyleSheet("QPushButton {\n"
"    background-color: #F3D8FF;\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    padding: 10px;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    font-family: \"Comic Sans MS\", cursive;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFDEB4;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F8A1C6;\n"
"}\n"
"\n"
"QFrame {\n"
"    border: 2px dashed #FFA4D1;\n"
"    border-radius: 10px;\n"
"}")
        self.donwloadPDF_button.setObjectName("donwloadPDF_button")
        self.horizontalLayout_5.addWidget(self.donwloadPDF_button)
        self.main_menu_frame = QtWidgets.QFrame(self.exam_results)
        self.main_menu_frame.setGeometry(QtCore.QRect(1410, 870, 341, 111))
        self.main_menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_menu_frame.setObjectName("main_menu_frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.main_menu_frame)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.main_menu_btn = QtWidgets.QPushButton(self.main_menu_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_menu_btn.sizePolicy().hasHeightForWidth())
        self.main_menu_btn.setSizePolicy(sizePolicy)
        self.main_menu_btn.setStyleSheet("QPushButton {\n"
"    background-color: #F3D8FF;\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    padding: 10px;\n"
"    font-size: 40px;\n"
"    font-weight: bold;\n"
"    font-family: \"Comic Sans MS\", cursive;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #F6EEA1;\n"
"    font-size: 50px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F8A1C6;\n"
"    font-size: 50px;\n"
"}\n"
"\n"
"QFrame {\n"
"    border: 2px dashed #FFA4D1;\n"
"    border-radius: 10px;\n"
"}")
        self.main_menu_btn.setObjectName("main_menu_btn")
        self.verticalLayout_9.addWidget(self.main_menu_btn)
        self.screens_stack.addWidget(self.exam_results)
        self.terms_condition_screen = QtWidgets.QWidget()
        self.terms_condition_screen.setStyleSheet("QWidget#terms_condition_screen {\n"
"border-image: url(:/bg/background.jpg) 0 0 0 0 stretch stretch;\n"
"}")
        self.terms_condition_screen.setObjectName("terms_condition_screen")
        self.terms_condition_textEdit = QtWidgets.QTextEdit(self.terms_condition_screen)
        self.terms_condition_textEdit.setGeometry(QtCore.QRect(450, 230, 1161, 631))
        self.terms_condition_textEdit.setStyleSheet("QTextEdit{\n"
"background-color: rgba(0, 0, 0,50);\n"
"border: 3px solid black;\n"
"border-radius: 25px;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"}")
        self.terms_condition_textEdit.setReadOnly(True)
        self.terms_condition_textEdit.setObjectName("terms_condition_textEdit")
        self.start_exam_frame_2 = QtWidgets.QFrame(self.terms_condition_screen)
        self.start_exam_frame_2.setGeometry(QtCore.QRect(130, 890, 341, 111))
        self.start_exam_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.start_exam_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.start_exam_frame_2.setObjectName("start_exam_frame_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.start_exam_frame_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.back_start_exam1_btn = QtWidgets.QPushButton(self.start_exam_frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_start_exam1_btn.sizePolicy().hasHeightForWidth())
        self.back_start_exam1_btn.setSizePolicy(sizePolicy)
        self.back_start_exam1_btn.setStyleSheet("QPushButton#back_start_exam1_btn {\n"
"    background-color: #F3D8FF;\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    padding: 10px;\n"
"    font-size: 40px;\n"
"    font-weight: bold;\n"
"    font-family: \"Comic Sans MS\", cursive;\n"
"}\n"
"\n"
"QPushButton:hover#back_start_exam1_btn {\n"
"    background-color: #F6EEA1;\n"
"    font-size: 50px;\n"
"}\n"
"\n"
"\n"
"QFrame#start_exam_btn {\n"
"    border: 2px dashed #FFA4D1;\n"
"    border-radius: 10px;\n"
"}")
        self.back_start_exam1_btn.setObjectName("back_start_exam1_btn")
        self.verticalLayout_10.addWidget(self.back_start_exam1_btn)
        self.screens_stack.addWidget(self.terms_condition_screen)
        self.message_center_screen = QtWidgets.QWidget()
        self.message_center_screen.setObjectName("message_center_screen")
        self.screens_stack.addWidget(self.message_center_screen)
        self.setup_gear_screen = QtWidgets.QWidget()
        self.setup_gear_screen.setStyleSheet("QWidget#setup_gear_screen {\n"
"border-image: url(:/bg/background.jpg) 0 0 0 0 stretch stretch;\n"
"}")
        self.setup_gear_screen.setObjectName("setup_gear_screen")
        self.terms_condition_textEdit_2 = QtWidgets.QTextEdit(self.setup_gear_screen)
        self.terms_condition_textEdit_2.setGeometry(QtCore.QRect(490, 40, 1391, 941))
        self.terms_condition_textEdit_2.setStyleSheet("QTextEdit{\n"
"background-color: rgba(255, 255, 255,200);\n"
"border: 3px solid black;\n"
"border-radius: 25px;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"padding-top: 10px;\n"
"}")
        self.terms_condition_textEdit_2.setReadOnly(True)
        self.terms_condition_textEdit_2.setObjectName("terms_condition_textEdit_2")
        self.start_exam_frame_3 = QtWidgets.QFrame(self.setup_gear_screen)
        self.start_exam_frame_3.setGeometry(QtCore.QRect(130, 890, 341, 111))
        self.start_exam_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.start_exam_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.start_exam_frame_3.setObjectName("start_exam_frame_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.start_exam_frame_3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.back_start_exam1_btn_2 = QtWidgets.QPushButton(self.start_exam_frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_start_exam1_btn_2.sizePolicy().hasHeightForWidth())
        self.back_start_exam1_btn_2.setSizePolicy(sizePolicy)
        self.back_start_exam1_btn_2.setStyleSheet("QPushButton {\n"
"    background-color: #F3D8FF;\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    padding: 10px;\n"
"    font-size: 40px;\n"
"    font-weight: bold;\n"
"    font-family: \"Comic Sans MS\", cursive;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #F6EEA1;\n"
"    font-size: 50px;\n"
"}\n"
"\n"
"\n"
"QFrame {\n"
"    border: 2px dashed #FFA4D1;\n"
"    border-radius: 10px;\n"
"}")
        self.back_start_exam1_btn_2.setObjectName("back_start_exam1_btn_2")
        self.verticalLayout_11.addWidget(self.back_start_exam1_btn_2)
        self.screens_stack.addWidget(self.setup_gear_screen)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.screens_stack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startExamBtn.setText(_translate("MainWindow", "Start An Exam"))
        self.setGearBtn.setText(_translate("MainWindow", "Setup Gear"))
        self.msgCenterBtn.setText(_translate("MainWindow", "Message Center"))
        self.exitBtn.setText(_translate("MainWindow", "Exit"))
        self.label.setText(_translate("MainWindow", "AutiVision"))
        self.headline1_label.setText(_translate("MainWindow", "Toddler\'s information:"))
        self.name_label.setText(_translate("MainWindow", "Name:"))
        self.age_label.setText(_translate("MainWindow", "Age:"))
        self.gender_label.setText(_translate("MainWindow", "Gender:"))
        self.gender_cb.setItemText(0, _translate("MainWindow", "Male"))
        self.gender_cb.setItemText(1, _translate("MainWindow", "Female"))
        self.contact_label.setText(_translate("MainWindow", "Contact information:"))
        self.email_label.setText(_translate("MainWindow", "Email:"))
        self.checkBox.setText(_translate("MainWindow", "I have read and agreed to the"))
        self.terms_condition_btn.setText(_translate("MainWindow", "terms and conditions"))
        self.start_exam_btn.setText(_translate("MainWindow", "Start"))
        self.headline.setText(_translate("MainWindow", "Observation is Done"))
        self.email_sent_label.setText(_translate("MainWindow", "We have sent an email with the results to "))
        self.directD_label.setText(_translate("MainWindow", "Alternatively, the results can be downloaded here:"))
        self.donwloadPDF_button.setText(_translate("MainWindow", "Download PDF"))
        self.main_menu_btn.setText(_translate("MainWindow", "Main Menu"))
        self.terms_condition_textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600; text-decoration: underline;\">Terms and Conditions Agreement</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">This Terms and Conditions Agreement (the &quot;Agreement&quot;) is a legal agreement between you (the &quot;User&quot;) and AutiVision (the &quot;Company&quot;), governing your use of the eyetracking program (the &quot;Program&quot;) and the associated AI algorithm (the &quot;Algorithm&quot;). By accessing or using the Program, you agree to be bound by the terms and conditions set forth in this Agreement.</span></p>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:14pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20px;\">Acceptance of Terms By using the Program, you acknowledge that you have read, understood, and agreed to be bound by the terms and conditions of this Agreement. If you do not agree with any of the terms and conditions, you must not use the Program.</span></li>\n"
"<li style=\" font-size:14pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20px;\">User Consent 2.1 User Consent for Eyetracking In order to use the Program, you hereby provide your explicit consent for the Program to access and use your eyetracking data. The Program will use an eyetracker device to monitor your eye movements and collect data during the diagnostic process.</span></li></ol>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">2.2 User Consent for AI Algorithm You also acknowledge and consent to the use of the AI algorithm to analyze and interpret your eyetracking data in order to generate results. The Algorithm uses advanced artificial intelligence techniques to provide accurate and reliable diagnostic information.</span></p>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:14pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20px;\">Data Collection and Privacy 3.1 Data Collection The Program will collect and store your eyetracking data, including but not limited to eye movement patterns, gaze direction, and pupil dilation. This data will be used solely for the purpose of generating accurate diagnostic results.</span></li></ol>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">3.2 Data Privacy and Security The Company is committed to protecting your privacy and ensuring the security of your data. All collected data will be handled in accordance with our Privacy Policy, which is hereby incorporated into this Agreement. The Privacy Policy outlines the types of data collected, how it is used, and how it is protected.</span></p>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:14pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20px;\">Diagnostic Results 4.1 Accuracy of Results While the Algorithm strives to provide accurate diagnostic results, it is important to note that the Program\'s results are generated based on AI analysis and should not be considered as a substitute for professional medical advice. The Program is intended to assist healthcare professionals in their diagnostic process.</span></li></ol>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">4.2 Reliance on Results The Company shall not be held liable for any decisions made by the User or any third party based on the Program\'s diagnostic results. The User assumes all responsibility for the interpretation and use of the results.</span></p>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:14pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20px;\">Intellectual Property 5.1 Ownership The Program and the Algorithm, including all associated intellectual property rights, are owned and retained by the Company. This Agreement does not grant the User any ownership rights to the Program or the Algorithm.</span></li></ol>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">5.2 License The Company grants the User a limited, non-exclusive, non-transferable license to use the Program and the Algorithm solely for personal use and in accordance with this Agreement. The User may not modify, copy, distribute, sublicense, or reverse engineer the Program or the Algorithm.</span></p>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:14pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20px;\">Limitation of Liability To the extent permitted by applicable law, the Company shall not be liable for any direct, indirect, incidental, special, or consequential damages arising out of or in connection with the use or inability to use the Program, even if the Company has been advised of the possibility of such damages.</span></li>\n"
"<li style=\" font-size:14pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20px;\">Termination The Company reserves the right to terminate this Agreement and suspend or revoke the User\'s access to the Program at any time without prior notice, for any reason or no reason. Upon termination, the User must cease all use of the Program and delete any copies of the Program in their possession.</span></li>\n"
"<li style=\" font-size:14pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20px;\">Governing Law and Jurisdiction This Agreement shall be governed by and construed in accordance with the laws of Jurisdiction. Any disputes arising out of or relating to this Agreement shall be subject to the exclusive jurisdiction of the courts</span></li></ol></body></html>"))
        self.back_start_exam1_btn.setText(_translate("MainWindow", "Back"))
        self.terms_condition_textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt; font-weight:600;\">Setup Eye Tracker Software &amp; Gear</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:36pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; text-decoration: underline;\">Step 1:</span><span style=\" font-size:22pt;\"> Download \'Tobii Eye Tracker 4c Core Software\' </span><a href=\"https://gaming.tobii.com/getstarted/\"><span style=\" font-size:22pt; text-decoration: underline; color:#0000ff;\">From here</span></a></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:26pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/setupGear/setup_step1.1.jpg\" /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; text-decoration: underline;\">Step 2:</span><span style=\" font-size:22pt;\"> Install \'Tobii Eye Tracker 4c\' Application</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:22pt; text-decoration: underline; color:#0000ff;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/setupGear/setup_step2.jpg\" /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; text-decoration: underline;\">Step 3:</span><span style=\" font-size:22pt;\"> Reach the tobii Eyetracking appication &amp; click \'Display Setup\'</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:22pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/setupGear/setup_step4.jpg\" /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; text-decoration: underline;\">Step 4:</span><span style=\" font-size:22pt;\"> Follow the instructions</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:22pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/setupGear/setup_step3.jpg\" /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; text-decoration: underline;\">Step 5:</span><span style=\" font-size:22pt;\"> Test &amp; Improve Calibration</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:22pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/setupGear/setup_step5.jpg\" /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:22pt;\"><br /></p></body></html>"))
        self.back_start_exam1_btn_2.setText(_translate("MainWindow", "Back"))
import rec_rc
